sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2


language: scala

matrix:
  include:
  - scala: 2.11.8
    jdk: oraclejdk7
  - scala: 2.11.8
    jdk: openjdk7
  - scala: 2.11.8
    jdk: oraclejdk8
  - scala: 2.11.8
    jdk: openjdk8
  - scala: 2.12.1
    jdk: oraclejdk8
  - scala: 2.12.1
    jdk: openjdk8

notifications:
  email:
    - filippo.deluca@ovoenergy.com
