sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2


language: scala

scala:
   - 2.11.8
   - 2.12.1

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk8
  - openjdk7

matrix:
  exclude:
  - scala: 2.12.1
    jdk: oraclejdk7
  - scala: 2.12.1
    jdk: openjdk7

notifications:
  email:
    - filippo.deluca@ovoenergy.com
