sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2


language: scala

env:
  global:
  - TEST_TIMEFACTOR=3.0

scala:
  - 2.11.8
  - 2.12.1

jdk:
  - oraclejdk8

notifications:
  email:
    - filippo.deluca@ovoenergy.com
